Update audit.yml (#10)

diff --git a/.github/workflows/audit.yml b/.github/workflows/audit.yml
--- a/.github/workflows/audit.yml
+++ b/.github/workflows/audit.yml
@@ -18,9 +18,19 @@ jobs:
       - name: Build
         run: |
           npm run build
-      - name: Run Lighthouse CI
+      - name: Waiting for 200 from the Netlify Preview
+        uses: josephduffy/wait-for-netlify-action@v1
+        id: wait-for-netflify-preview
+        with:
+          site_name: "phq9"
+      - name: Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.6.x
-          lhci autorun --upload.target=temporary-public-storage"
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+      - name: Save results
+        uses: actions/upload-artifact@master
+        with:
+          name: lighthouse-results
+          path: '.lighthouseci'
